language: objective-c
osx_image: xcode9.4
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - IOS_SDK=iphonesimulator11.4
script:
  - xcodebuild -showsdks
  - xcodebuild -workspace Position.xcworkspace -scheme 'Debug' -sdk $IOS_SDK build analyze

