language: objective-c
osx_image: xcode11.5
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - IOS_SDK=iphonesimulator13.5
script:
  - xcodebuild -showsdks
  - xcodebuild -workspace Position.xcworkspace -scheme 'Debug' -sdk $IOS_SDK build analyze
